# Generated by Django 3.0.2 on 2020-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChestACCX', models.FloatField()),
                ('ChestACCY', models.FloatField()),
                ('ChestACCZ', models.FloatField()),
                ('ChestECG', models.FloatField()),
                ('ChestResp', models.FloatField()),
                ('WristACCX', models.FloatField()),
                ('WristACCY', models.FloatField()),
                ('WristACCZ', models.FloatField()),
                ('WristBVP', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Gender', models.FloatField()),
                ('Age', models.FloatField()),
                ('Height', models.FloatField()),
                ('Sport', models.FloatField()),
                ('activity', models.FloatField(null=True)),
            ],
        ),
    ]
